добавил задачи 2-ого модуля
js-tasks-ru/jsbasic-20210906-2_tkhvds pull request #4
Opened 2021-09-15 18:41 UTC by TikhonovDanila

Добавлены задачи 1,2,3

2021-09-15 18:42 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-15 19:31 UTC, SinimaWath requested changes

2021-09-15 19:31 UTC, SinimaWath commented on 2-module/1-task/index.js
> +};
Давай уберем этот код

2021-09-15 19:31 UTC, SinimaWath commented on 2-module/3-task/index.js
> +    this.NumberA = +a;
обычно свойства в js классах нахывают с маленькой буквы

2021-09-15 19:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-16 20:09 UTC, SinimaWath approved these changes

2021-09-16 20:09 UTC, merged